# Generated by Django 3.2.6 on 2021-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_singermodel_songmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='singermodel',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
