# Generated by Django 3.2.6 on 2021-09-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_singermodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singermodel',
            name='gender',
        ),
    ]
