# Generated by Django 3.2.6 on 2021-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='createdBy',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
