# Generated by Django 3.2.6 on 2021-09-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentmodel_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
