# Generated by Django 3.2.6 on 2021-09-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210909_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='api.singermodel'),
        ),
    ]
